function [fitresult, gof] = curveFit(y_points, x_points)
%CREATEFIT(Y_POINTS,X_POINTS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: y_points
%      Y Output: x_points
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Mar-2023 18:31:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( y_points, x_points );

% Set up fittype and options.
ft = fittype( 'poly4' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'x_points vs. y_points', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'y_points', 'Interpreter', 'none' );
ylabel( 'x_points', 'Interpreter', 'none' );
grid on


